-- Q1. Total revenue generated by male vs female customers
SELECT 
    gender,
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Customers who used a discount but spent more than average purchase amount
WITH avg_purchase AS (
    SELECT AVG(purchase_amount) AS avg_amount
    FROM customer
)
SELECT 
    c.customer_id,
    c.purchase_amount
FROM customer c, avg_purchase a
WHERE c.discount_applied = 'Yes'
  AND c.purchase_amount >= a.avg_amount;

-- Q3. Top 5 products with highest average review rating
SELECT 
    item_purchased,
    ROUND(AVG(CAST(review_rating AS NUMERIC)), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY "Average Product Rating" DESC
LIMIT 5;

-- Q4. Average purchase amount for Standard and Express shipping
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
GROUP BY shipping_type
HAVING shipping_type = 'Standard'
    OR shipping_type = 'Express';

-- Q5. Average spend and total revenue for subscribers vs non-subscribers
SELECT 
    subscription_status,
    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue ASC, avg_spend DESC;

-- Q6. Top 5 products with highest discount purchase percentage
SELECT 
    item_purchased,
    ROUND(
        AVG(
            CASE 
                WHEN discount_applied = 'Yes' THEN 100.0
                ELSE 0
            END
        ), 2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Customer segmentation based on previous purchases
SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(customer_id) AS "Number of Customers"
FROM customer
GROUP BY 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END;

-- Q8. Top 3 most purchased products within each category
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
) ranked_items
WHERE item_rank <= 3;

-- Q9. Repeat buyers and their subscription status
SELECT 
    subscription_status,
    COUNT(*) AS repeat_buyers
FROM customer
GROUP BY subscription_status
HAVING COUNT(*) FILTER (WHERE previous_purchases > 5) > 0;


-- Q10. Revenue contribution of each age group
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY SUM(purchase_amount) DESC;